spring:
  redis:
    host: locahost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis_test
    username: test_user
    password: 1234

logging:
  level:
    org:
      hibernate:
        SQL: debug


