spring:
  profiles:
    group:
      "chaos-monkey": "local, chaos-monkey"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test_user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor: debug # trace: sql 내용 분석용
