spring:
  profiles:
    group:
      "default": "local, db"

  cache:
    type: redis
    redis:
      time-to-live: 60000 #ms
      cache-null-values: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: debug