version: "3"

#  $ docker run -d -p 3307:3306 --name mysqldb -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=test mysql
#  docker run -p 9090:8080 --name app --net spring-net -e MYSQL_HOST=mysqldb -e MYSQL_USER=root -e MYSQL_PASSWORD=root -e MYSQL_PORT=3306 app
services:
  mysql:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - spring-net

  app:
    image: app
    container_name: app
    build: .
    restart: always
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - 9090:8080
    depends_on:
      - mysql
    networks:
      - spring-net

networks:
  spring-net: