spring:
  profiles:
    default: local
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}

logging:
  level:
    org:
      springframework:
        batch: debug
